name: Build web/android/windows apps
on:
  push:
    branches: [ "master" ]

jobs:
  build_windows_app:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: del pubspec.lock
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: '${{github.event.repository.name}}-windows.zip'
          directory: build/windows/runner/Release
      - run: mkdir build/windows/runner/Release/result
      - run: move build/windows/runner/Release/${{github.event.repository.name}}-windows.zip build/windows/runner/Release/result
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/windows/runner/Release/result add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:buildWin --force

      

  build_web_and_android_app:
    needs: build_windows_app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: rm -f pubspec.lock
      - run: flutter pub get
      - run: flutter config --enable-web --enable-android
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com

      - run: flutter build web --base-href "/${{ github.event.repository.name }}/"
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh_pages --force

      - run: flutter build apk --release
      - run: mkdir build/app/outputs/flutter-apk/result
      - run: mv build/app/outputs/flutter-apk/app-*.apk build/app/outputs/flutter-apk/result/${{github.event.repository.name}}.apk
      - run: git --work-tree build/app/outputs/flutter-apk/result add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:buildAPK --force